POST http://localhost:3000/api/offers
content-type: application/json

{
    
    "title":"Super fast boat",
    "mobile":"1212121212",
    "category":"sale",
    "description":"New boat",
    "location":"Szczecin/PL",
    "price":"123"
}

###

POST http://localhost:3000/api/users
content-type: application/json

{
    
    "email":"john@onet.pl",
    "password":"12344523",
    "fullName":"John Stacton"
    
}

###
GET http://localhost:3000/api/offers/paginate

###
GET http://localhost:3000/api/products
###

POST http://localhost:3000/api/checkout
content-type: application/json

{
   "id":"recivYqubBjGZDicn",
   "offerId": 15,
   "quantity": 1
   
}

###
POST http://localhost:3000/api/users/resetPassword
content-type: application/json

{
    "email": "admin@admin.pl"
}

###
PUT http://localhost:3000/api/users/resetPassword
content-type: application/json

{
    "resetToken": "c6c88c760b6102c746a6bf6b4d41a90ac4a086db02d0",
    "password": "karol123"
}

###
PUT http://localhost:3000/api/offers/31/toogleFavorite